#pragma once

//Projects
#define IPM_SUPERIOR_CRAFTING 1.2
#define IPM_ADVANCED_CRAFTER 1.2
#define IMP_CRAFTING_EFFICIENCY (1/0.8)

//Ships
#define IMP_ELDERSHIP_K 1.5
#define IMP_THUNDERHORSE_K 2

//Mothership bonuses
#define IPM_SHIP_SMELL_SPEED 3.0
#define IPM_SHIP_CRAFT_SPEED 3.6
#define IPM_SHIP_SMELL_RESOURCE_K 2.0
#define IPM_SHIP_CRAFT_RESOURCE_K 2.0
#define IPM_SHIP_PROJECT_RESOURCE_K (1/(1-0.38))

//Stattion bonuses
//#define IPM_STATION_SMELT_BONUS 1
#define IPM_STATION_CRAFT_SPEED_BONUS 1.01

#define IPM_SMELT_RESOURCE_K (1.2 * IPM_SHIP_SMELL_RESOURCE_K)
#define IPM_CRAFT_RESOURCE_K (IMP_CRAFTING_EFFICIENCY * IPM_SHIP_CRAFT_RESOURCE_K)
#define IPM_PROJECT_RESOURCE_K (IPM_SHIP_PROJECT_RESOURCE_K)

#define IPM_LEADER_SMELT_BONUS 2.01
#define IPM_LEADER_CRAFT_BONUS 9.72

#define IPM_SMELT_TIME_K (1.2 * IMP_ELDERSHIP_K * IMP_THUNDERHORSE_K * IPM_LEADER_SMELT_BONUS * IPM_SHIP_SMELL_SPEED)
#define IPM_CRAFT_TIME_K (IPM_ADVANCED_CRAFTER * IPM_SUPERIOR_CRAFTING * IPM_LEADER_CRAFT_BONUS * IMP_ELDERSHIP_K * IMP_THUNDERHORSE_K * IPM_SHIP_CRAFT_SPEED * IPM_STATION_CRAFT_SPEED_BONUS)
#define IPM_CRAFT_COUNT 8
#define IPM_SMELT_COUNT 10