#pragma once

#define IMP_ELDERSHIP_K 1.5
#define IPM_SMELT_RESOURCE_K 0.8
#define IPM_CRAFT_RESOURCE_K 0.8
#define IPM_SMELT_TIME_K (1.2*IMP_ELDERSHIP_K)
#define IPM_CRAFT_TIME_K (1.2*1.2*1.59*IMP_ELDERSHIP_K)
#define IPM_CRAFT_COUNT 9